CREATE TABLE [dbo].[Accounts] (
    [Id]       INT        IDENTITY (1, 1) NOT NULL,
    [USERNAME] NCHAR (40) NULL,
    [PASSWORD] NCHAR (40) NULL,
    [ROLE] NCHAR(10) NULL, 
    [FIRSTNAME] NCHAR(10) NULL, 
    [LASTNAME] NCHAR(10) NULL, 
    [EMAIL] NCHAR(10) NULL, 
    [DATECREATED] DATETIME NULL, 
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

